[package]
name = "executor"

version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9.1"    

substring = "1.0"
json = "0.12.4"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.48"
rustc_version_runtime = "0.1.*"
    
fixed_decimal = {version="0.5.0"}
writeable =  {version="0.5.0"}

icu = { version="1.0.0", features = ["serde"] }
icu_testdata = { version="1.0.0", features = ["metadata"] }
icu_provider = { version="1.0.0"}

[features]
