name: dartweb
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0-39.0.dev

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^2.4.0
  intl4x:
    git:
      url: https://github.com/dart-lang/i18n.git
      path: pkgs/intl4x/
      ref: addIntl4x

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
