/* Generate listformat test data with the following dimensions:

   1. locale
   2. type (conjunction, disjunction, unit)
   3. style (long, short, narrow)
*/

// Set up Node version to generate data specific to ICU/CLDR version
// e.g., `nvm install 21.6.0;nvm use 21.6.0` (ICU 74)

const fs = require('node:fs');

const debug = false;

const locales = ['und',
                 'en-US', 'zh-TW', 'pt', 'vi', 'el', 'mt-MT', 'ru', 'en-GB',
                 'bn', 'ar','mr', 'zu'];

const types = ['conjunction', 'disjunction', 'unit'];

const styles = ['long', 'short', 'narrow'];

const lists = [
  [],
  ['cat'],
  ['dog', 'cat'],
  ['fish', 'mouse', 'parakeet'],
  ['3 weeks', '2 days', '3 hours', '25 minutes']
];

function generateAll() {

  let test_obj = {
    'Test scenario': 'list_fmt',
    'test_type': 'list_fmt',
    'description': 'list format test data generated by Node',
    'platformVersion': process.version,
    'icuVersion': process.versions.icu,
    'cldrVersion': process.versions.cldr
  };

  let test_cases = [];

  let verify_obj = {
    'test_type': 'list_fmt',
    'description': 'list format test data generated by Node',
    'platformVersion': process.version,
    'icuVersion': process.versions.icu,
    'cldrVersion': process.versions.cldr
  }
  let verify_cases = [];

  let label_num = 0;

  const expected_count = locales.length * types.length * styles.length *
        lists.length;

  console.log("Generating ", expected_count, " list_fmt tests for ", process.versions.icu);

  for (const locale of locales) {

    for (const type of types) {

      for (const style of styles) {

        // Create format object with these options
        let all_options = {
          'style': style,
          'type': type
        }

        let formatter;
        try {
          formatter = new Intl.ListFormat(locale, all_options);
        } catch (error) {
          console.log(error, ' with locale ',
                      locale, ' and options: ', all_options);
          continue;
        }

        for (const list of lists) {
          try {
            result = formatter.format(list);
          } catch (error) {
            console.log('FORMATTER CREATION FAILS! ', error);
          }

          const label_string = String(label_num);
          // TODO: Save this as a test case.
          let test_case = {'label': label_string,
                           'input_list': list,
                           'options': {...all_options}
                          };

          if (locale != '') {
            test_case["locale"] = locale;
          }

          if (debug) {
            console.log("TEST CASE :", test_case);
          }
          test_cases.push(test_case);

          // Generate what we get.
          try{
            verify_cases.push({'label': label_string,
                               'verify': result});
            if (debug) {
              console.log('   expected = ', result);
            }
          } catch (error) {
            console.log('!!! error ', error, ' in label ', label_num,
                        ' for options ', options, ' and list ', list);
          }
          label_num ++;
        };
      }
    }
  }


  console.log('Number of tests generated for ',
              process.versions.icu, ': ', label_num);

  test_obj['tests'] = test_cases;
  try {
    fs.writeFileSync('list_fmt_test.json', JSON.stringify(test_obj, null, 2));
    // file written successfully
  } catch (err) {
    console.error(err);
  }

  verify_obj['verifications'] = verify_cases;
  try {
    fs.writeFileSync('list_fmt_verify.json', JSON.stringify(verify_obj, null, 2));
    // file written successfully
  } catch (err) {
    console.error(err);
  }
}

/* Call the generator */
generateAll();
