include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  errors:
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_single_quotes
    - sort_pub_dependencies
    - unnecessary_parenthesis
    - avoid_dynamic_calls
    - type_annotate_public_apis
    - non_constant_identifier_names
    - prefer_final_locals
    - unnecessary_this
