on: [push]

name: CI

jobs:
  rust_lint:
    name: Lint the rust executor code on submission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path executors/rust/Cargo.toml
  
