on:
  push:
    paths:
    - 'executors/rust/**'
  pull_request:
    paths: 
    - 'executors/rust/**'

name: Rust CI

jobs:
  rust_lint:
    name: Lint the rust executor code on submission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path executors/rust/Cargo.toml
  
